name = "muzichka-master-lista"
main = "src/pr-worker.js"
compatibility_date = "2023-10-02"

[vars]
# Optional defaults; can be set as secrets too
GITHUB_OWNER = "martinpetkovski"
GITHUB_REPO = "masterlista"
GITHUB_DEFAULT_BRANCH = "master"
## Comma-separated list of allowed origins for CORS
CORS_ORIGINS = "https://toplista.mk,https://www.toplista.mk,https://www.najjak.com,https://martinpetkovski.github.io"
